# ML Cup Event #3

In [ ]:
!pip install pandas
!pip install numpy
!pip install pycaret
import pandas as pd
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.22.2.post1.


In [3]:
import os
os.getcwd()

'/content'

In [4]:

from google.colab import files
upload = files.upload()
upload1 = files.upload()

Saving diabetes_train.csv to diabetes_train.csv


Saving diabetes_test.csv to diabetes_test.csv


In [13]:
df = pd.read_csv("diabetes_train.csv")
df_test = pd.read_csv("diabetes_test.csv")

Id_col = 'Id'
target_col = 'diabetes'
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Id                  576 non-null    int64  
 1   num_times_pregnant  576 non-null    int64  
 2   plasma_glucose      576 non-null    int64  
 3   DBP                 576 non-null    int64  
 4   triceps_skin        576 non-null    int64  
 5   serum_insulin       576 non-null    int64  
 6   BMI                 576 non-null    float64
 7   pedigree            576 non-null    float64
 8   age                 576 non-null    int64  
 9   diabetes            576 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 45.1 KB


Id  num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age  diabetes
0  358                  13             129    0  ...  39.9     0.569   44         1
1   74                   4             129   86  ...  35.1     0.231   23         0
2  353                   3              61   82  ...  34.4     0.243   46         0
3  498                   2              81   72  ...  30.1     0.547   25         0
4  146                   0             102   75  ...   0.0     0.572   21         0

[5 rows x 10 columns]

In [12]:
import pandas_profiling
pandas_profiling.ProfileReport(df)

OSError: ignored

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop([Id_col, target_col], axis=1)
y = df[target_col]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X.info()
X.shape
X.head()

X_train.info()
X_train.shape
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  576 non-null    int64  
 1   plasma_glucose      576 non-null    int64  
 2   DBP                 576 non-null    int64  
 3   triceps_skin        576 non-null    int64  
 4   serum_insulin       576 non-null    int64  
 5   BMI                 576 non-null    float64
 6   pedigree            576 non-null    float64
 7   age                 576 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 36.1 KB


(576, 8)

num_times_pregnant  plasma_glucose  DBP  triceps_skin  serum_insulin   BMI  \
0                  13             129    0            30              0  39.9   
1                   4             129   86            20            270  35.1   
2                   3              61   82            28              0  34.4   
3                   2              81   72            15             76  30.1   
4                   0             102   75            23              0   0.0   

   pedigree  age  
0     0.569   44  
1     0.231   23  
2     0.243   46  
3     0.547   25  
4     0.572   21

<class 'pandas.core.frame.DataFrame'>
Int64Index: 460 entries, 437 to 102
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  460 non-null    int64  
 1   plasma_glucose      460 non-null    int64  
 2   DBP                 460 non-null    int64  
 3   triceps_skin        460 non-null    int64  
 4   serum_insulin       460 non-null    int64  
 5   BMI                 460 non-null    float64
 6   pedigree            460 non-null    float64
 7   age                 460 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 32.3 KB


(460, 8)

num_times_pregnant  plasma_glucose  DBP  triceps_skin  serum_insulin  \
437                   6             102   82             0              0   
63                    7             142   60            33            190   
208                   1             119   44            47             63   
60                    8             143   66             0              0   
15                    0             123   88            37              0   

      BMI  pedigree  age  
437  30.8     0.180   36  
63   28.8     0.687   61  
208  35.5     0.280   25  
60   34.9     0.129   41  
15   35.2     0.197   29

In [ ]:
np.bincount(y)

array([377, 199], dtype=int64)

# Build Model

In [ ]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=2)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

# Estimate Model Performance

In [ ]:
from sklearn.metrics import confusion_matrix

pred_val = clf.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

array([[78,  3],
       [19, 16]], dtype=int64)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

F1 Score = 0.59

              precision    recall  f1-score   support

           0       0.80      0.96      0.88        81
           1       0.84      0.46      0.59        35

    accuracy                           0.81       116
   macro avg       0.82      0.71      0.73       116
weighted avg       0.82      0.81      0.79       116



# Create Submission File on Test Data

In [ ]:
test_df = pd.read_csv('diabetes_test.csv')

# Make sure to transform/create the features the same way you did for training
# For now, nothing to do

X_test = test_df.drop([Id_col], axis=1)

# Use your model to make predictions
pred_test = clf.predict(X_test)

# We will look at the predicted prices to ensure we have something sensible.
print(pred_test)

my_submission = pd.DataFrame({'Id': test_df.Id, 'Predicted': pred_test})

my_submission.head()

# you could use any filename. We choose submission here
my_submission.to_csv('my_submission.csv', index=False)

[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0
 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0]


Id  Predicted
0  669          0
1  325          0
2  625          0
3  691          0
4  474          0